### ISSUE TITLE
Всплывающее окно кнопки "Сбросить прогресс"

### ISSUE THREAD

**Issue by skulikovs** [tima2015/Color-it#15]
![Screenshot_20211210-184547_Color-it](https://user-images.githubusercontent.com/72536774/145583709-a0169f0d-243a-47ee-8238-05edeb4d2944.jpg)
После нажатия кнопки "Сбросить прогресс", есть возможность нажать мимо всплывающего окна, непосредственно на окно настроек позади, что переводит всплывающее окно на задний план. Таким образом возможно множественное нажатие на кнопку "Сбросить прогресс", создавая затемнение экрана.

**Comment by tima2015** [comment]
Ошибка заключалась в неверно заданном флаге модальности всплывающих окон. Исправлено в последнем коммите
